# Generated by Django 5.1.1 on 2024-10-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convenience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('parent', models.IntegerField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('EQUIPMENT', 'Equipment'), ('CONVENIENCE', 'Convenience')], default=None, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('priority', models.IntegerField(blank=True, default=None, null=True)),
                ('code', models.CharField(blank=True, default=None, max_length=40, null=True)),
            ],
        ),
    ]
