# Generated by Django 4.2.11 on 2024-05-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenience',
            name='type',
            field=models.CharField(choices=[('PR', 'PRODUCT'), ('PO', 'POLICY')], default='PR', max_length=2),
        ),
    ]
