# Generated by Django 4.2.11 on 2024-06-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convenience', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convenience',
            name='value',
        ),
    ]
