# Generated by Django 5.0.2 on 2024-03-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenience',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='convenience',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='convenience',
            name='parent',
            field=models.BigIntegerField(null=True),
        ),
    ]
