# Generated by Django 4.2.11 on 2024-06-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenience', '0002_remove_convenience_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenience',
            name='type',
            field=models.CharField(blank=True, choices=[('PR', 'PRODUCT'), ('PO', 'POLICY')], default='PR', max_length=2, null=True),
        ),
    ]
