# Generated by Django 4.2.11 on 2024-06-18 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convenience', '0003_alter_convenience_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convenience',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='convenience',
            name='type',
        ),
    ]
