# Generated by Django 4.2.11 on 2024-05-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenience', '0003_convenience_created_at_alter_convenience_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenience',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='convenience',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='convenience',
            name='parent',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
