# Generated by Django 4.2.11 on 2024-05-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenience', '0004_alter_convenience_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenience',
            name='parent',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
