# Generated by Django 5.1.1 on 2024-10-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenience', '0004_remove_convenience_is_free_remove_convenience_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenience',
            name='type',
            field=models.CharField(choices=[('EQUIPMENT', 'Equipment'), ('CONVENIENCE', 'Convenience')], default=None, max_length=20, null=True),
        ),
    ]
