# Generated by Django 4.2.11 on 2024-05-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenience', '0005_alter_convenience_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenience',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
