# Generated by Django 4.2.11 on 2024-05-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenience', '0007_alter_convenience_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenience',
            name='value',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
