# Generated by Django 5.1.1 on 2024-10-06 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeRegion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('code_name', models.CharField(max_length=50)),
                ('code_name_en', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AdministrativeUnit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=80)),
                ('full_name_en', models.CharField(max_length=80)),
                ('short_name', models.CharField(max_length=50)),
                ('short_name_en', models.CharField(max_length=50)),
                ('code_name', models.CharField(max_length=80)),
                ('code_name_en', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('full_name_en', models.CharField(max_length=100, null=True)),
                ('code_name', models.CharField(max_length=50, null=True)),
                ('administrative_region', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.administrativeregion')),
                ('administrative_unit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.administrativeunit')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('full_name_en', models.CharField(max_length=100, null=True)),
                ('code_name', models.CharField(max_length=50, null=True)),
                ('administrative_unit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.administrativeunit')),
                ('province_code', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.province')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('full_name_en', models.CharField(max_length=100, null=True)),
                ('code_name', models.CharField(max_length=50, null=True)),
                ('administrative_unit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.administrativeunit')),
                ('district_code', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.district')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.district')),
                ('province', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='location.province')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.ward')),
            ],
        ),
    ]
