# Generated by Django 4.2.11 on 2024-06-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
