# Generated by Django 4.2.11 on 2024-06-02 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_city_country_district_ward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='postal_code',
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.city'),
        ),
        migrations.AlterField(
            model_name='location',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.district'),
        ),
        migrations.AlterField(
            model_name='location',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.ward'),
        ),
    ]
