# Generated by Django 4.2.11 on 2024-06-13 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_administrativeregions_administrativeunits_provinces_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdministrativeRegions',
            new_name='AdministrativeRegion',
        ),
        migrations.RenameModel(
            old_name='AdministrativeUnits',
            new_name='AdministrativeUnit',
        ),
        migrations.RenameModel(
            old_name='Provinces',
            new_name='Province',
        ),
    ]
