# Generated by Django 4.2.11 on 2024-06-03 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('convenience', '0008_alter_convenience_value'),
        ('organization', '0002_remove_organization_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='conveniences',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='organizations', to='convenience.convenience'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL),
        ),
    ]
