# Generated by Django 5.1.1 on 2024-10-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_description_organization_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
