# Generated by Django 5.1.1 on 2024-10-12 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organization_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='type',
            new_name='organization_type',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
