# Generated by Django 4.2.11 on 2024-06-19 16:05

from django.db import migrations, models
import tutorial.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_privatedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(storage=tutorial.storage_backends.PublicMediaStorage(), upload_to='')),
            ],
        ),
    ]
