# Generated by Django 4.2.11 on 2024-05-24 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('asset', '0002_alter_assetmodel_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_id', to='organization.organization'),
        ),
    ]
