INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (1, 'Nhà vệ sinh', 'test', true, 37);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (2, 'Bồn tắm hoặc Vòi sen', 'test', true, 37);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (3, 'Khăn tắm', 'test', true, 37);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (4, 'Ra trải giường', 'advadv', true, 36);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (5, 'Ổ điện gần giường ', 'test', true, 39);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (6, 'Sản phẩm lau rửa', 'test', true, 34);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (7, 'Không gây dị ứng Sàn lát gạch/đá cẩm thạch', 'test', true, 39);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (8, 'Bàn làm việc', 'test', true, 52);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (9, 'Khu vực tiếp khách', 'test', true, 52);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (10, 'Bàn ủi li quần', 'test', true, 39);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (11, 'Tủ lạnh', 'test', true, 34);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (12, 'TV', 'test', true, 38);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (13, 'Truyền hình vệ tinh', 'test', true, 38);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (14, 'Toilet chung', 'test', true, 37);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (15, 'Máy sấy tóc', 'test', true, 37);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (16, 'Ổ cắm cho iPod', 'test', true, 38);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (17, 'Ấm đun nước điện', 'test', true, 34);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (18, 'Bàn ăn', 'test', true, 34);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (19, 'Giá treo quần áo', 'test', true, 39);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (20, 'Giá phơi quần áo', 'test', true, 39);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (21, 'Giấy vệ sinh', 'test', true, 37);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (22, 'Máy lọc không khí', 'test', true, 39);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (23, 'Dép', 'test', true, 37);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (24, 'Quạt máy', 'test', true, 39);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (25, 'Toilet phụ', 'test', true, 37);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (26, 'Lò vi sóng', 'test', true, 34);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (29, 'Điều hòa không khí', 'test', true, 39);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (30, 'Phòng tắm riêng', 'test', true, 37);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (31, 'TV màn hình phẳng', 'test', true, 38);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (32, 'Hệ thống cách âm', 'test', true, 39);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (33, 'WiFi miễn phí', 'test', true, NULL);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (34, 'Nhà bếp', 'test', true, NULL);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (35, 'Chỗ đậu xe', 'test', true, NULL);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (36, 'Phòng ngủ', 'test', true, NULL);
INSERT INTO convenience_convenience (id, name, description, is_active, parent) VALUES (37, 'Phòng tắm', 'test', true, NULL);