# Generated by Django 5.1.1 on 2024-10-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='type',
            field=models.CharField(choices=[('SEX', 'SEX'), ('CATEGORY_REVIEW', 'CATEGORY_REVIEW'), ('RANK_POINT', 'RANK_POINT')], default=None, max_length=50, null=True),
        ),
    ]
