# Generated by Django 4.2.11 on 2024-06-03 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_organization_address_and_more'),
        ('service', '0004_alter_service_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='organization.organization'),
        ),
    ]
