# Generated by Django 4.2.11 on 2024-06-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=10, unique=True)),
                ('discount', models.DecimalField(decimal_places=1, max_digits=100)),
                ('discount_type', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='code',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='discount_type',
        ),
        migrations.AddField(
            model_name='promotion',
            name='promotions',
            field=models.ManyToManyField(to='promotion.promotionitem'),
        ),
    ]
