# Generated by Django 5.0.2 on 2024-03-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='pin_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
