# Generated by Django 5.0.2 on 2024-03-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'ordered'), ('APPROVED', 'approved'), ('IN_PROCESS', 'in process'), ('END_PROCESS', 'end process'), ('COMPLETED', 'completed'), ('PENDING', 'pending'), ('CANCEL', 'cancel')], default='ORDERED', max_length=30),
        ),
    ]
