# Generated by Django 5.1.1 on 2024-10-12 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_status'),
        ('service', '0002_remove_service_location_alter_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='organization',
        ),
        migrations.AddField(
            model_name='reservation',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='service.service'),
        ),
    ]
