# Generated by Django 4.2.11 on 2024-06-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_service_organization'),
        ('reservation', '0003_remove_reservation_evaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='rooms',
        ),
        migrations.AddField(
            model_name='reservation',
            name='services',
            field=models.ManyToManyField(related_name='reservations', to='service.service'),
        ),
    ]
