# Generated by Django 4.2.11 on 2024-06-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_service_organization'),
        ('reservation', '0004_remove_reservation_rooms_reservation_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='services',
            field=models.ManyToManyField(related_name='reservations', related_query_name='reservation', to='service.service'),
        ),
    ]
