# Generated by Django 5.1.1 on 2024-10-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_remove_reservation_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='service',
        ),
    ]
