# Generated by Django 5.1.1 on 2024-10-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_remove_reservation_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('CANCEL', 'CANCEL'), ('ORDERED', 'ORDERED'), ('COMPLETED', 'COMPLETED'), ('CLOSE', 'CLOSE')], default=None, max_length=30, null=True),
        ),
    ]
